#Flutterアプリで使用する依存パッケージやアセットを管理するための設定ファイル

name: quiz_app
description: A simple quiz application for iOS and Android.

# Flutter SDK version
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies used in the project
dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.3.1  # 状態管理
  sqflite: ^2.2.0        # ローカルデータベース
  path_provider: ^2.0.12 # データ保存パス取得用
  flutter_hooks: ^0.18.0 # ウィジェットライフサイクル最適化

# Dev dependencies for testing and debugging
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.0           # コード規約

# Assets for the project
flutter:
  uses-material-design: true
  assets:
    - assets/images/     # 画像ファイル
    - assets/sounds/     # 音声ファイル
